# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14tCOIxCgdDAu_UqQT5t3ZVfotJUAmQPS
"""

def soundex(word):
    soundex = word[0]
    for x in word[1:]:
        if x in ['b', 'f', 'p', 'v']:
            soundex += '1'
        elif x in ['c', 'g', 'j', 'k', 'q', 's', 'x', 'z']:
            soundex += '2'
        elif x in ['d', 't']:
            soundex += '3'
        elif x in ['l']:
            soundex += '4'
        elif x in ['m', 'n']:
            soundex += '5'
        elif x in ['r']:
            soundex += '6'
    soundex = (soundex + '0000')[:4]

    return soundex